dmjio/stripe

src/Web/Stripe/Client/Types.hs

The current definition prevents Stripe from being used as a base monad because GHC complains about the type synonym missing a type parameter. This should allow for more flexible use of the Stripe monad.
For example, I'm wiring up pipes to the API, and can't currently write this:
```
allCustomers :: Producer [Customer] Stripe ()
```

Allow Stripe monad to be used as a base in transformer stack

---

src/Web/Stripe/Subscription.hs
stripe-haskell.cabal
tests/Test/Discount.hs
tests/Test/Subscription.hs

Partial solution to #10 .  I know that there is a big rework of API parameters in a separate pull request ( #11 ) but it seems like that has stalled.  In the mean time, this will allow `updateSubscription` to be used to update plans.  I update the test code and the relevant section passes.

Added Maybe PlanId to updateSubscription

---

src/Web/Stripe/Client/Internal.hs
tests/Test/Raw.hs

Today I ran into an issue with special characters in a request. For example:
If I call the `createCustomerBase` function with an '&' in the Description field, the POST body is incorrectly formatted.
I noticed the API is using x-www-form-urlencoded but not encoding the parameters: https://github.com/dmjio/stripe/blob/859dde23aaad776763c55ef4015c01eaff225f8e/src/Web/Stripe/Client/Util.hs#L50
The ruby library encodes the strings: https://github.com/stripe/stripe-ruby/blob/782a596c8f01060d22b44151e9dbd60a8ef138d6/lib/stripe.rb#L120. I believe the Python library url encodes requests as well. 
I've included a test case using the raw API which will fail without the `encodedFormBody` function. I believe the behavior of `encodedFormBody` is very similar to the `Builder.fromByteString` and …

URL encode form params in x-www-form-urlencode POST body.

---

.travis.yml

Allowed failures for GHC 7.10 and GHC HEAD.

Update travis build to support multiple ghc versions.

---

stripe-haskell/src/Web/Stripe.hs

It looks like there is a typo on one of the examples in the docs, SecretKey does not seem to exist, but StripeConfig appears to do what this wants

fix example in to use correct config constructor

---

.travis.yml

As suggested in the [stack guide](https://github.com/commercialhaskell/stack/blob/master/doc/GUIDE.md#travis-with-caching)

Use latest version of stack in travis job

---

stripe-core/stripe-core.cabal
stripe-http-streams/stripe-http-streams.cabal
stripe-tests/stripe-tests.cabal

This makes it compatible with the latest stackage nightly (`nightly-2016-10-26`).

Bump aeson upper bound to 1.1.*

---

stripe-core/src/Web/Stripe/Subscription.hs

Looking at the [stripe docs](https://stripe.com/docs/api/node#create_subscription-prorate), `prorate` appears to be a valid parameter for the `CreateSubscription` API.

Add Prorate param to CreateSubscription

---

.travis.yml

Some GHC builds should be allowed to fail

Allow failures

---

stripe-core/src/Web/Stripe/Types.hs

Running
```
stripe (StripeConfig (StripeKey "xxx")) $ getInvoiceItems -&- CustomerId "xxx"
```
gives
```
Left (StripeError {errorType = ParseFailure, errorMsg = "mzero", errorCode = Nothing, errorParam = Nothing, errorHTTP = Nothing})
```
I tracked this down to the `invoiceItemSubscription` entry on [InvoiceItem](https://hackage.haskell.org/package/stripe-core-2.1.0/docs/Web-Stripe-InvoiceItem.html#t:InvoiceItem). If you look at the stripe API for invoice items https://stripe.com/docs/api#invoiceitem_object,
the subscription value of an invoice item is the subscriptionId as a string.  But the type of
`invoiceItemSubscription` field is `Subscription` so we are trying to parse a string like "sub_xxxx"
into a Subscription.  To fix tis, the type of `invoiceItemSubscription` must change to …

Use correct type for invoiceItemSubscription

---

README.md
stripe-haskell/README.md

GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1

Fix broken headings in Markdown files

---

stripe-core/src/Web/Stripe/Types.hs

Cards have a `metadata` field which was not included.

Added metadata from cards

---

stripe-core/src/Web/Stripe/Subscription.hs
stripe-tests/tests/Web/Stripe/Test/Subscription.hs

This renames the current `getSubscriptions` to `getSubscriptionsByCustomerId` and introduces a new `getSubscriptions`:
``` haskell
-- | Retrieve all active `Subscription`s
getSubscriptions
:: StripeRequest GetSubscriptions
```
which retrieves all the subscriptions (for all customers). 
Fixes #83

Retrieve all subscriptions

---

.travis.yml
stack.yaml
stripe-http-client/LICENSE
stripe-http-client/Setup.hs
stripe-http-client/src/Web/Stripe/Client/HttpClient.hs
stripe-http-client/stripe-http-client.cabal
stripe-http-client/tests/Main.hs

fixes #90 
This is some initial work I've done to implement an `http-client` backend for stripe requests. I wanted to get some feedback before I commit too much time to "finalizing" it for merge.
**Notes:**
- I used `http-client` instead of `http-conduit`. I don't use `http-conduit` much myself and don't really know yet what a `stripe-http-conduit` library may look like.
- I add `stripeConn` and `withConnection` for API compatibility so that existing clients using stripe-http-streams could plug this in without any necessary changes. However, http-client's terminology regarding "connections" is different than http-streams. I'm considering adding DEPRECATED pragmas to these specific functions to get people to use the `stripeManager` and `withManager` function to avoid confusion. I don't …

Implement http-client backend for stripe requests

---

stripe-core/stripe-core.cabal
stripe-http-client/stripe-http-client.cabal
stripe-http-streams/stripe-http-streams.cabal
stripe-tests/stripe-tests.cabal

This builds for me, though I am not yet actually using the stripe library.  But it is hard to see why it would be unsafe.

Allow aeson-1.3

---

.travis.yml
default.nix

Adds `8.4.4` to travis, builds `8.4.4` by default.

Bump to 8.4.4

---

stripe-core/src/Web/Stripe/Types.hs

Fairly self explanatory: I was receiving an `UnknownEvent` type, and noticed there was an "r" missing.

Fix typo charge.failed in FromJSON EventType

---

stripe-core/src/Web/Stripe/InvoiceItem.hs

It is a trivial addition and it is part of the API since long before this version so there is no reason not to have it.

Add ability to get invoice items for a specific Invoice

---

stripe-tests/tests/Web/Stripe/Test/Prelude.hs

I believe since GHC 8.0.1 we need to import `fail` and `MonadFail` from
`Control.Monad.Fail` instead of `Control.Monad`. I also believe that
this is a temporary measure, and this changes again from GHC 8.8.1.
More:
- https://downloads.haskell.org/~ghc/8.0.2/docs/html/users_guide/glasgow_exts.html#ghc-flag--XMonadFailDesugaring
- https://wiki.haskell.org/MonadFail_Proposal

Fix MonadFail import

---

stripe-core/default.nix
stripe-haskell/default.nix
stripe-http-client/default.nix
stripe-http-streams/default.nix
stripe-tests/default.nix

The version numbers in all of the default.nix files were lagging behind
the version numbers stated in the cabal files. This mismatch was causing
some confusing behaviour when I tried to build these packages locally.
I refreshed the versions and dependencies by running cabal2nix in each
of the sub-projects.

Fix dependencies and versions in Nix expressions

---

stripe-core/src/Web/Stripe/Types.hs

This commit brings this library's credit/debit card brand parser into
alignment with the values specified in Stripe's API documentation. This
also removes the `mzero` so that the cause of a parse failure here is
more obvious to a library user.
More specifically, this fixes two issues:
1. We incorrectly parsed Diners Club cards, which I believe is the cause
of [issue #129][0]
2. We did not support UnionPay cards at all.
[0]: https://github.com/dmjio/stripe/issues/129

Align CC brands with Stripe API

---

stripe-tests/stripe-tests.cabal

This PR updates bounds for random-1.2 which was released about a year ago.
If possible a new revision on hackage would be awesome, since it is blocking commercialhaskell/stackage#5474

Update bounds for random
